# Generated by Django 5.1.2 on 2024-11-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categorie',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
